//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import RswiftResources
import UIKit

private class BundleFinder {}
let R = _R(bundle: Bundle(for: BundleFinder.self))

struct _R {
  let bundle: Foundation.Bundle
  var color: color { .init(bundle: bundle) }
  var image: image { .init(bundle: bundle) }
  var info: info { .init(bundle: bundle) }
  var file: file { .init(bundle: bundle) }
  var storyboard: storyboard { .init(bundle: bundle) }

  func color(bundle: Foundation.Bundle) -> color {
    .init(bundle: bundle)
  }
  func image(bundle: Foundation.Bundle) -> image {
    .init(bundle: bundle)
  }
  func info(bundle: Foundation.Bundle) -> info {
    .init(bundle: bundle)
  }
  func file(bundle: Foundation.Bundle) -> file {
    .init(bundle: bundle)
  }
  func storyboard(bundle: Foundation.Bundle) -> storyboard {
    .init(bundle: bundle)
  }
  func validate() throws {
    try self.storyboard.validate()
  }

  struct project {
    let developmentRegion = "en"
  }

  /// This `_R.color` struct is generated, and contains static references to 1 colors.
  struct color {
    let bundle: Foundation.Bundle

    /// Color `AccentColor`.
    var accentColor: RswiftResources.ColorResource { .init(name: "AccentColor", path: [], bundle: bundle) }
  }

  /// This `_R.image` struct is generated, and contains static references to 77 images.
  struct image {
    let bundle: Foundation.Bundle

    /// Image `icon_button_github`.
    var icon_button_github: RswiftResources.ImageResource { .init(name: "icon_button_github", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_button_star`.
    var icon_button_star: RswiftResources.ImageResource { .init(name: "icon_button_star", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_button_unstar`.
    var icon_button_unstar: RswiftResources.ImageResource { .init(name: "icon_button_unstar", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_button_user_plus`.
    var icon_button_user_plus: RswiftResources.ImageResource { .init(name: "icon_button_user_plus", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_button_user_x`.
    var icon_button_user_x: RswiftResources.ImageResource { .init(name: "icon_button_user_x", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_cell_acknowledgements`.
    var icon_cell_acknowledgements: RswiftResources.ImageResource { .init(name: "icon_cell_acknowledgements", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_cell_badge_branch`.
    var icon_cell_badge_branch: RswiftResources.ImageResource { .init(name: "icon_cell_badge_branch", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_cell_badge_collaborator`.
    var icon_cell_badge_collaborator: RswiftResources.ImageResource { .init(name: "icon_cell_badge_collaborator", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_cell_badge_comment`.
    var icon_cell_badge_comment: RswiftResources.ImageResource { .init(name: "icon_cell_badge_comment", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_cell_badge_commit`.
    var icon_cell_badge_commit: RswiftResources.ImageResource { .init(name: "icon_cell_badge_commit", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_cell_badge_fork`.
    var icon_cell_badge_fork: RswiftResources.ImageResource { .init(name: "icon_cell_badge_fork", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_cell_badge_issue`.
    var icon_cell_badge_issue: RswiftResources.ImageResource { .init(name: "icon_cell_badge_issue", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_cell_badge_pull_request`.
    var icon_cell_badge_pull_request: RswiftResources.ImageResource { .init(name: "icon_cell_badge_pull_request", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_cell_badge_push`.
    var icon_cell_badge_push: RswiftResources.ImageResource { .init(name: "icon_cell_badge_push", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_cell_badge_repository`.
    var icon_cell_badge_repository: RswiftResources.ImageResource { .init(name: "icon_cell_badge_repository", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_cell_badge_search`.
    var icon_cell_badge_search: RswiftResources.ImageResource { .init(name: "icon_cell_badge_search", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_cell_badge_star`.
    var icon_cell_badge_star: RswiftResources.ImageResource { .init(name: "icon_cell_badge_star", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_cell_badge_tag`.
    var icon_cell_badge_tag: RswiftResources.ImageResource { .init(name: "icon_cell_badge_tag", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_cell_badge_trending`.
    var icon_cell_badge_trending: RswiftResources.ImageResource { .init(name: "icon_cell_badge_trending", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_cell_badge_user`.
    var icon_cell_badge_user: RswiftResources.ImageResource { .init(name: "icon_cell_badge_user", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_cell_check`.
    var icon_cell_check: RswiftResources.ImageResource { .init(name: "icon_cell_check", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_cell_cloc`.
    var icon_cell_cloc: RswiftResources.ImageResource { .init(name: "icon_cell_cloc", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_cell_company`.
    var icon_cell_company: RswiftResources.ImageResource { .init(name: "icon_cell_company", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_cell_contact_no_image`.
    var icon_cell_contact_no_image: RswiftResources.ImageResource { .init(name: "icon_cell_contact_no_image", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_cell_created`.
    var icon_cell_created: RswiftResources.ImageResource { .init(name: "icon_cell_created", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_cell_dir`.
    var icon_cell_dir: RswiftResources.ImageResource { .init(name: "icon_cell_dir", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_cell_disclosure`.
    var icon_cell_disclosure: RswiftResources.ImageResource { .init(name: "icon_cell_disclosure", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_cell_events`.
    var icon_cell_events: RswiftResources.ImageResource { .init(name: "icon_cell_events", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_cell_file`.
    var icon_cell_file: RswiftResources.ImageResource { .init(name: "icon_cell_file", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_cell_frown`.
    var icon_cell_frown: RswiftResources.ImageResource { .init(name: "icon_cell_frown", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_cell_git_branch`.
    var icon_cell_git_branch: RswiftResources.ImageResource { .init(name: "icon_cell_git_branch", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_cell_git_commit`.
    var icon_cell_git_commit: RswiftResources.ImageResource { .init(name: "icon_cell_git_commit", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_cell_git_fork`.
    var icon_cell_git_fork: RswiftResources.ImageResource { .init(name: "icon_cell_git_fork", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_cell_git_language`.
    var icon_cell_git_language: RswiftResources.ImageResource { .init(name: "icon_cell_git_language", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_cell_git_merge`.
    var icon_cell_git_merge: RswiftResources.ImageResource { .init(name: "icon_cell_git_merge", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_cell_git_pull_request`.
    var icon_cell_git_pull_request: RswiftResources.ImageResource { .init(name: "icon_cell_git_pull_request", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_cell_issues`.
    var icon_cell_issues: RswiftResources.ImageResource { .init(name: "icon_cell_issues", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_cell_language`.
    var icon_cell_language: RswiftResources.ImageResource { .init(name: "icon_cell_language", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_cell_link`.
    var icon_cell_link: RswiftResources.ImageResource { .init(name: "icon_cell_link", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_cell_logout`.
    var icon_cell_logout: RswiftResources.ImageResource { .init(name: "icon_cell_logout", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_cell_night_mode`.
    var icon_cell_night_mode: RswiftResources.ImageResource { .init(name: "icon_cell_night_mode", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_cell_profile_summary`.
    var icon_cell_profile_summary: RswiftResources.ImageResource { .init(name: "icon_cell_profile_summary", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_cell_readme`.
    var icon_cell_readme: RswiftResources.ImageResource { .init(name: "icon_cell_readme", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_cell_releases`.
    var icon_cell_releases: RswiftResources.ImageResource { .init(name: "icon_cell_releases", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_cell_remove`.
    var icon_cell_remove: RswiftResources.ImageResource { .init(name: "icon_cell_remove", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_cell_size`.
    var icon_cell_size: RswiftResources.ImageResource { .init(name: "icon_cell_size", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_cell_smile`.
    var icon_cell_smile: RswiftResources.ImageResource { .init(name: "icon_cell_smile", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_cell_source`.
    var icon_cell_source: RswiftResources.ImageResource { .init(name: "icon_cell_source", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_cell_star`.
    var icon_cell_star: RswiftResources.ImageResource { .init(name: "icon_cell_star", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_cell_stars_history`.
    var icon_cell_stars_history: RswiftResources.ImageResource { .init(name: "icon_cell_stars_history", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_cell_submodule`.
    var icon_cell_submodule: RswiftResources.ImageResource { .init(name: "icon_cell_submodule", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_cell_theme`.
    var icon_cell_theme: RswiftResources.ImageResource { .init(name: "icon_cell_theme", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_cell_updated`.
    var icon_cell_updated: RswiftResources.ImageResource { .init(name: "icon_cell_updated", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_cell_whats_new`.
    var icon_cell_whats_new: RswiftResources.ImageResource { .init(name: "icon_cell_whats_new", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_navigation_back`.
    var icon_navigation_back: RswiftResources.ImageResource { .init(name: "icon_navigation_back", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_navigation_close`.
    var icon_navigation_close: RswiftResources.ImageResource { .init(name: "icon_navigation_close", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_navigation_forward`.
    var icon_navigation_forward: RswiftResources.ImageResource { .init(name: "icon_navigation_forward", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_navigation_github`.
    var icon_navigation_github: RswiftResources.ImageResource { .init(name: "icon_navigation_github", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_navigation_history`.
    var icon_navigation_history: RswiftResources.ImageResource { .init(name: "icon_navigation_history", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_navigation_language`.
    var icon_navigation_language: RswiftResources.ImageResource { .init(name: "icon_navigation_language", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_navigation_refresh`.
    var icon_navigation_refresh: RswiftResources.ImageResource { .init(name: "icon_navigation_refresh", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_navigation_stop`.
    var icon_navigation_stop: RswiftResources.ImageResource { .init(name: "icon_navigation_stop", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_navigation_theme`.
    var icon_navigation_theme: RswiftResources.ImageResource { .init(name: "icon_navigation_theme", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_navigation_web`.
    var icon_navigation_web: RswiftResources.ImageResource { .init(name: "icon_navigation_web", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_tabbar_activity`.
    var icon_tabbar_activity: RswiftResources.ImageResource { .init(name: "icon_tabbar_activity", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_tabbar_login`.
    var icon_tabbar_login: RswiftResources.ImageResource { .init(name: "icon_tabbar_login", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_tabbar_news`.
    var icon_tabbar_news: RswiftResources.ImageResource { .init(name: "icon_tabbar_news", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_tabbar_profile`.
    var icon_tabbar_profile: RswiftResources.ImageResource { .init(name: "icon_tabbar_profile", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_tabbar_search`.
    var icon_tabbar_search: RswiftResources.ImageResource { .init(name: "icon_tabbar_search", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_tabbar_settings`.
    var icon_tabbar_settings: RswiftResources.ImageResource { .init(name: "icon_tabbar_settings", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_toast_error`.
    var icon_toast_error: RswiftResources.ImageResource { .init(name: "icon_toast_error", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_toast_success`.
    var icon_toast_success: RswiftResources.ImageResource { .init(name: "icon_toast_success", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_toast_warning`.
    var icon_toast_warning: RswiftResources.ImageResource { .init(name: "icon_toast_warning", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_whatsnew_cloc`.
    var icon_whatsnew_cloc: RswiftResources.ImageResource { .init(name: "icon_whatsnew_cloc", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_whatsnew_github`.
    var icon_whatsnew_github: RswiftResources.ImageResource { .init(name: "icon_whatsnew_github", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_whatsnew_theme`.
    var icon_whatsnew_theme: RswiftResources.ImageResource { .init(name: "icon_whatsnew_theme", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_whatsnew_trending`.
    var icon_whatsnew_trending: RswiftResources.ImageResource { .init(name: "icon_whatsnew_trending", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
  }

  /// This `_R.info` struct is generated, and contains static references to 1 properties.
  struct info {
    let bundle: Foundation.Bundle
    var uiApplicationSceneManifest: uiApplicationSceneManifest { .init(bundle: bundle) }

    func uiApplicationSceneManifest(bundle: Foundation.Bundle) -> uiApplicationSceneManifest {
      .init(bundle: bundle)
    }

    struct uiApplicationSceneManifest {
      let bundle: Foundation.Bundle

      let uiApplicationSupportsMultipleScenes: Bool = false

      var _key: String { bundle.infoDictionaryString(path: ["UIApplicationSceneManifest"], key: "_key") ?? "UIApplicationSceneManifest" }
      var uiSceneConfigurations: uiSceneConfigurations { .init(bundle: bundle) }

      func uiSceneConfigurations(bundle: Foundation.Bundle) -> uiSceneConfigurations {
        .init(bundle: bundle)
      }

      struct uiSceneConfigurations {
        let bundle: Foundation.Bundle
        var _key: String { bundle.infoDictionaryString(path: ["UIApplicationSceneManifest", "UISceneConfigurations"], key: "_key") ?? "UISceneConfigurations" }
        var uiWindowSceneSessionRoleApplication: uiWindowSceneSessionRoleApplication { .init(bundle: bundle) }

        func uiWindowSceneSessionRoleApplication(bundle: Foundation.Bundle) -> uiWindowSceneSessionRoleApplication {
          .init(bundle: bundle)
        }

        struct uiWindowSceneSessionRoleApplication {
          let bundle: Foundation.Bundle
          var defaultConfiguration: defaultConfiguration { .init(bundle: bundle) }

          func defaultConfiguration(bundle: Foundation.Bundle) -> defaultConfiguration {
            .init(bundle: bundle)
          }

          struct defaultConfiguration {
            let bundle: Foundation.Bundle
            var uiSceneConfigurationName: String { bundle.infoDictionaryString(path: ["UIApplicationSceneManifest", "UISceneConfigurations", "UIWindowSceneSessionRoleApplication"], key: "UISceneConfigurationName") ?? "Default Configuration" }
            var uiSceneDelegateClassName: String { bundle.infoDictionaryString(path: ["UIApplicationSceneManifest", "UISceneConfigurations", "UIWindowSceneSessionRoleApplication"], key: "UISceneDelegateClassName") ?? "$(PRODUCT_MODULE_NAME).SceneDelegate" }
            var uiSceneStoryboardFile: String { bundle.infoDictionaryString(path: ["UIApplicationSceneManifest", "UISceneConfigurations", "UIWindowSceneSessionRoleApplication"], key: "UISceneStoryboardFile") ?? "Main" }
          }
        }
      }
    }
  }

  /// This `_R.file` struct is generated, and contains static references to 43 resource files.
  struct file {
    let bundle: Foundation.Bundle

    /// Resource file `.swiftlint.yml`.
    var swiftlintYml: RswiftResources.FileResource { .init(name: ".swiftlint", pathExtension: "yml", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `EmptyArray.json`.
    var emptyArrayJson: RswiftResources.FileResource { .init(name: "EmptyArray", pathExtension: "json", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `EmptyObject.json`.
    var emptyObjectJson: RswiftResources.FileResource { .init(name: "EmptyObject", pathExtension: "json", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `Events.json`.
    var eventsJson: RswiftResources.FileResource { .init(name: "Events", pathExtension: "json", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `EventsOrganization.json`.
    var eventsOrganizationJson: RswiftResources.FileResource { .init(name: "EventsOrganization", pathExtension: "json", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `EventsRepository.json`.
    var eventsRepositoryJson: RswiftResources.FileResource { .init(name: "EventsRepository", pathExtension: "json", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `EventsUserPerformed.json`.
    var eventsUserPerformedJson: RswiftResources.FileResource { .init(name: "EventsUserPerformed", pathExtension: "json", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `EventsUserReceived.json`.
    var eventsUserReceivedJson: RswiftResources.FileResource { .init(name: "EventsUserReceived", pathExtension: "json", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `Languages.json`.
    var languagesJson: RswiftResources.FileResource { .init(name: "Languages", pathExtension: "json", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `Notifications.json`.
    var notificationsJson: RswiftResources.FileResource { .init(name: "Notifications", pathExtension: "json", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `NotificationsRepository.json`.
    var notificationsRepositoryJson: RswiftResources.FileResource { .init(name: "NotificationsRepository", pathExtension: "json", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `Organization.json`.
    var organizationJson: RswiftResources.FileResource { .init(name: "Organization", pathExtension: "json", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `Profile.json`.
    var profileJson: RswiftResources.FileResource { .init(name: "Profile", pathExtension: "json", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `Repository.json`.
    var repositoryJson: RswiftResources.FileResource { .init(name: "Repository", pathExtension: "json", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `RepositoryBranch.json`.
    var repositoryBranchJson: RswiftResources.FileResource { .init(name: "RepositoryBranch", pathExtension: "json", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `RepositoryBranches.json`.
    var repositoryBranchesJson: RswiftResources.FileResource { .init(name: "RepositoryBranches", pathExtension: "json", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `RepositoryCommit.json`.
    var repositoryCommitJson: RswiftResources.FileResource { .init(name: "RepositoryCommit", pathExtension: "json", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `RepositoryCommits.json`.
    var repositoryCommitsJson: RswiftResources.FileResource { .init(name: "RepositoryCommits", pathExtension: "json", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `RepositoryContents.json`.
    var repositoryContentsJson: RswiftResources.FileResource { .init(name: "RepositoryContents", pathExtension: "json", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `RepositoryContributors.json`.
    var repositoryContributorsJson: RswiftResources.FileResource { .init(name: "RepositoryContributors", pathExtension: "json", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `RepositoryForks.json`.
    var repositoryForksJson: RswiftResources.FileResource { .init(name: "RepositoryForks", pathExtension: "json", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `RepositoryIssue.json`.
    var repositoryIssueJson: RswiftResources.FileResource { .init(name: "RepositoryIssue", pathExtension: "json", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `RepositoryIssueComments.json`.
    var repositoryIssueCommentsJson: RswiftResources.FileResource { .init(name: "RepositoryIssueComments", pathExtension: "json", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `RepositoryIssues.json`.
    var repositoryIssuesJson: RswiftResources.FileResource { .init(name: "RepositoryIssues", pathExtension: "json", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `RepositoryNumberOfLines.json`.
    var repositoryNumberOfLinesJson: RswiftResources.FileResource { .init(name: "RepositoryNumberOfLines", pathExtension: "json", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `RepositoryPullRequest.json`.
    var repositoryPullRequestJson: RswiftResources.FileResource { .init(name: "RepositoryPullRequest", pathExtension: "json", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `RepositoryPullRequestComments.json`.
    var repositoryPullRequestCommentsJson: RswiftResources.FileResource { .init(name: "RepositoryPullRequestComments", pathExtension: "json", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `RepositoryPullRequests.json`.
    var repositoryPullRequestsJson: RswiftResources.FileResource { .init(name: "RepositoryPullRequests", pathExtension: "json", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `RepositoryReadme.json`.
    var repositoryReadmeJson: RswiftResources.FileResource { .init(name: "RepositoryReadme", pathExtension: "json", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `RepositoryRelease.json`.
    var repositoryReleaseJson: RswiftResources.FileResource { .init(name: "RepositoryRelease", pathExtension: "json", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `RepositoryReleases.json`.
    var repositoryReleasesJson: RswiftResources.FileResource { .init(name: "RepositoryReleases", pathExtension: "json", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `RepositorySearch.json`.
    var repositorySearchJson: RswiftResources.FileResource { .init(name: "RepositorySearch", pathExtension: "json", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `RepositoryStargazers.json`.
    var repositoryStargazersJson: RswiftResources.FileResource { .init(name: "RepositoryStargazers", pathExtension: "json", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `RepositoryTrendings.json`.
    var repositoryTrendingsJson: RswiftResources.FileResource { .init(name: "RepositoryTrendings", pathExtension: "json", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `RepositoryWatchers.json`.
    var repositoryWatchersJson: RswiftResources.FileResource { .init(name: "RepositoryWatchers", pathExtension: "json", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `User.json`.
    var userJson: RswiftResources.FileResource { .init(name: "User", pathExtension: "json", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `UserFollowers.json`.
    var userFollowersJson: RswiftResources.FileResource { .init(name: "UserFollowers", pathExtension: "json", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `UserFollowing.json`.
    var userFollowingJson: RswiftResources.FileResource { .init(name: "UserFollowing", pathExtension: "json", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `UserRepositories.json`.
    var userRepositoriesJson: RswiftResources.FileResource { .init(name: "UserRepositories", pathExtension: "json", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `UserRepositoriesStarred.json`.
    var userRepositoriesStarredJson: RswiftResources.FileResource { .init(name: "UserRepositoriesStarred", pathExtension: "json", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `UserRepositoriesWatching.json`.
    var userRepositoriesWatchingJson: RswiftResources.FileResource { .init(name: "UserRepositoriesWatching", pathExtension: "json", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `UserSearch.json`.
    var userSearchJson: RswiftResources.FileResource { .init(name: "UserSearch", pathExtension: "json", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `UserTrendings.json`.
    var userTrendingsJson: RswiftResources.FileResource { .init(name: "UserTrendings", pathExtension: "json", bundle: bundle, locale: LocaleReference.none) }
  }

  /// This `_R.storyboard` struct is generated, and contains static references to 2 storyboards.
  struct storyboard {
    let bundle: Foundation.Bundle
    var launchScreen: launchScreen { .init(bundle: bundle) }
    var main: main { .init(bundle: bundle) }

    func launchScreen(bundle: Foundation.Bundle) -> launchScreen {
      .init(bundle: bundle)
    }
    func main(bundle: Foundation.Bundle) -> main {
      .init(bundle: bundle)
    }
    func validate() throws {
      try self.launchScreen.validate()
      try self.main.validate()
    }


    /// Storyboard `LaunchScreen`.
    struct launchScreen: RswiftResources.StoryboardReference, RswiftResources.InitialControllerContainer {
      typealias InitialController = UIKit.UIViewController

      let bundle: Foundation.Bundle

      let name = "LaunchScreen"
      func validate() throws {

      }
    }

    /// Storyboard `Main`.
    struct main: RswiftResources.StoryboardReference, RswiftResources.InitialControllerContainer {
      typealias InitialController = ViewController

      let bundle: Foundation.Bundle

      let name = "Main"
      func validate() throws {

      }
    }
  }
}